spring:
  # 数据源
  datasource:
    #    要用druid池就要加上druid依赖
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cms?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
      username: root
      password: 123456

  #返回统一格式的时间json字符串
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    # 控制台打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    设置日志级别
    # 配置驼峰映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.zaxxer: error
#    com.briup: debug